[package]
name = "hc_zome_email_notifications_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
